#!/usr/bin/env bash
# Runs on the VPS after `git fetch` + `git reset --hard` (shared family-deploy).
# Writes js/buildInfo.js so the shared footer can render the release version.
# The file is generated per-deploy and gitignored — do not commit it.
set -euo pipefail

VERSION="$(git describe --tags --abbrev=0 2>/dev/null || true)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || true)"

cat > js/buildInfo.js <<EOF
/* Generated by scripts/deploy.sh on the VPS — do not edit or commit. */
window.BUILD_INFO = { version: '${VERSION}', commit: '${COMMIT}' };
EOF

echo "Wrote js/buildInfo.js (version=${VERSION:-none}, commit=${COMMIT:-none})"
